name: musiz_player
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audio_service: ^0.18.17
  audio_video_progress_bar: ^2.0.3
  dart_des: ^1.0.2
  eva_icons_flutter: ^3.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  iconsax: ^0.0.8
  just_audio: ^0.9.46
  sliding_up_panel: ^2.0.0+1
  provider: ^6.1.2
  duration_picker: ^1.2.0
  flutter_displaymode: ^0.6.0
  google_fonts: any
  http: any
  logging: any
  flutter_swipe_action_cell: ^3.1.5
  hive: ^2.2.3
  flutter_colorpicker: ^1.1.0
  dropdown_button2: ^2.3.9
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  dynamic_color: ^1.7.0
  flutter_lyric: ^2.0.4+6
  flip_card: ^0.7.0
  permission_handler: ^11.4.0
  flutter_progress_status: ^0.0.4
  path_provider: ^2.1.5
  youtube_explode_dart: ^2.3.10
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  shared_preferences: ^2.5.2
  country_picker: ^2.0.27
  url_launcher: ^6.3.1
  intl: any
  just_audio_mpv: ^0.1.7
  bitsdojo_window: ^0.1.6
  titlebar_buttons: ^1.0.0
  palette_generator: ^0.3.3+6
  metadata_god: ^1.0.0
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/